# Generated by Django 5.2.7 on 2026-07-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='needs_manager_approval',
            field=models.BooleanField(default=False),
        ),
    ]
